// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmAbHEn2yxMyQMZtc0Jmyzep66zZvSKTo',
    appId: '1:494663723412:web:75617ed766ed0d13990781',
    messagingSenderId: '494663723412',
    projectId: 'productivity-app-d194c',
    authDomain: 'productivity-app-d194c.firebaseapp.com',
    databaseURL: 'https://productivity-app-d194c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'productivity-app-d194c.appspot.com',
    measurementId: 'G-M6DB85R6T2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8Dky1TPkZfe57IW-VS2QtMSgweMpLYtE',
    appId: '1:494663723412:android:0f3887da92f1aed3990781',
    messagingSenderId: '494663723412',
    projectId: 'productivity-app-d194c',
    databaseURL: 'https://productivity-app-d194c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'productivity-app-d194c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeMZMfcXBISPXe81fHnV3MwRjWKdHubww',
    appId: '1:494663723412:ios:f95f54ff850cfa61990781',
    messagingSenderId: '494663723412',
    projectId: 'productivity-app-d194c',
    databaseURL: 'https://productivity-app-d194c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'productivity-app-d194c.appspot.com',
    iosClientId: '494663723412-eo39in2s98hn8f4ati32ektjkd0lhh2e.apps.googleusercontent.com',
    iosBundleId: 'com.example.testenv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeMZMfcXBISPXe81fHnV3MwRjWKdHubww',
    appId: '1:494663723412:ios:f95f54ff850cfa61990781',
    messagingSenderId: '494663723412',
    projectId: 'productivity-app-d194c',
    databaseURL: 'https://productivity-app-d194c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'productivity-app-d194c.appspot.com',
    iosClientId: '494663723412-eo39in2s98hn8f4ati32ektjkd0lhh2e.apps.googleusercontent.com',
    iosBundleId: 'com.example.testenv',
  );
}
